### ISSUE TITLE
[OpenSoTIk] WALK-MAN sprint_week_october

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/MiscellaneousPlugins#2]
Hi all,
I use this issue to track the status of this plugin for the final WALK-MAN demo.
Today we experienced couple of behaviors that we may don't like.
1.  Problems in reaching certain height with the valve task
2. Jerky motion

For what regards these two points, maybe adding the waist_orient task (in the last commit of sprint_week_october) we are over-constraining the motion, furthermore this could result in a more complicated stack (that means that the solve takes more times and we brake the timing/RT).
From the point of view of context switch anyway looks everything fine.

Furthermore I found an issue with the joint velocity limits:
1. line 117:
```_joint_vel_lims.reset( new OpenSoT::constraints::velocity::VelocityLimits(qdotlims, 0.001) );```
the 0.001 should be changed to the period of the plugin because we are not going for sure at 1KHz with the actual stack.

So I will suggest to remove the waist_orient task and check if the tracking of the height of the valve task goes better. Maybe we can also increase joint_velocity_limits (M_PI ?) and decrease the lambda of the Cartesian Tasks to 0.1.

We are also loggin the generated joint velocities so we can easily check if trajectories are smooth (if not I think we should remove the postural task).

**Comment by EnricoMingo** [comment]
Also:
we should compare the desired joint trajectory with the performed one to have an idea of the tracking (to better understand which ar is better and which one to use for the tasks)

**Comment by liesrock** [comment]
Since the walkman demo was successful I close this, but thanks for keeping tracks.
