### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by MartijnZ** [ADVRHumanoids/MiscellaneousPlugins#4]
Hi,

I'm new (and lost) in the use of XBotCore. Instead of directly asking a colleague at IIT, I open an issue such that other newcomers might benefit from its answer.

* What do I want to achieve?
I want to develop a XBotCore Plugin, lets call it ```HelloXBotCore``` (for simplicity)

* What Am I Looking for?
A recipe which answers the following:
    1) How to develop a plugin? What is it structure?
    2)  How to use a plugin? How compile and run it?

    The first question is answered by browsing trough the examples in this repo. For example  ```Homing.cpp``` demonstrates all the functions needed to use the realtime loop. 
Yet, this doesn't demonstrate how to use a plugin. For example, how to compile the plugin? I'm not able to compile the MiscellaneousPlugins repo on its own (It only (partly) compiles in the advr superbuild). What 'magic' does the superbuild add such that is able to compile? What does it take to compile ```HelloXBotCore```?

I understand the Wiki is still under development. I'm happy to contribute with a ```HelloXBotCore``` tutorial, once I figured out the above. Until then, any hints to the above will be appreciated!

Martijn

**Comment by MartijnZ** [comment]
I created a first version of HelloXBotCore, you can find the wiki in the corresponding repo:
https://github.com/MartijnZ/HelloXBotCore/wiki

**Comment by liesrock** [comment]
I will close this since @MartijnZ unfortunately disappeared.
